name: Deploy to Vercel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps chromium
        
      - name: Run linting
        run: pnpm lint

      - name: Build Design System package
        if: ${{ success() }}
        run: pnpm build:ds
        
      - name: Run Design System tests
        if: ${{ success() }}
        run: pnpm --filter "@lateral/design-system" test

      - name: Build Task Manager app
        if: ${{ success() }}
        run: pnpm --filter "@lateral/task-manager" build
        
      - name: Run Task Manager tests
        # if: ${{ success() }}
        # Temporarily disabled due to Error: Vitest failed to find the runner. This is a bug in Vitest. Please, open an issue with reproduction.
        if: false 
        run: pnpm --filter "@lateral/task-manager" test

      - name: Deploy to Vercel
        if: ${{ success() }}
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./packages/task-manager
          vercel-args: '--prod'
